#!/bin/bash

## For ovs-vswitchd service, we assume openvswitch, vport_gre,
##  vport_vxlan and vport_geneve kernel modules are already 
##  loaded by the system OS

case $1 in
        "ovsdb-server") /usr/share/openvswitch/scripts/ovs-ctl start \
                        --system-id=random --no-ovs-vswitchd
                        /usr/share/openvswitch/scripts/ovs-ctl stop
                        ovsdb-server --pidfile /etc/openvswitch/conf.db \
                        -vconsole:emer -vsyslog:err -vfile:info \
                        --remote=punix:/var/run/openvswitch/db.sock \
                        --private-key=db:Open_vSwitch,SSL,private_key \
                        --certificate=db:Open_vSwitch,SSL,certificate \
                        --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert \
                        --log-file=/var/log/openvswitch/ovsdb-server.log \
                        --no-chdir
        ;;
        "ovs-vswitchd") /usr/share/openvswitch/scripts/ovs-ctl \
                        --no-ovsdb-server start
                        /usr/share/openvswitch/scripts/ovs-ctl \
                        --no-ovsdb-server force-reload-kmod
                        /usr/share/openvswitch/scripts/ovs-ctl stop
                        ovs-vswitchd --pidfile -vconsole:emer -vsyslog:err \
                        -vfile:info --mlockall --no-chdir \
                        --log-file=/var/log/openvswitch/ovs-vswitchd.log
        ;;
        *) echo "$0 [ovsdb-server|ovs-vswitchd]"
esac
